# toml file for ollama-hertz

title = "TOML config for ollama-hertz"

[server]
port = ":8080"

[redis]
addr = "localhost:6379"
password = ""
db = 0

[mysql]
dsn = "root:09161549@(localhost:3306)/ollama?charset=utf8&parseTime=True"

[ollama]
model = "llama3"
serverUrl = "http://192.168.0.107:11434"